USE [master]
GO

/****** Object:  Database [Recdit]    Script Date: 10/29/2020 11:33:18 AM ******/
CREATE DATABASE [Recdit]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Recdit', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Recdit.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Recdit_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Recdit_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Recdit].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Recdit] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Recdit] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Recdit] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Recdit] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Recdit] SET ARITHABORT OFF 
GO

ALTER DATABASE [Recdit] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Recdit] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Recdit] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Recdit] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Recdit] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Recdit] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Recdit] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Recdit] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Recdit] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Recdit] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Recdit] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Recdit] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Recdit] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Recdit] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Recdit] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Recdit] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Recdit] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Recdit] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Recdit] SET  MULTI_USER 
GO

ALTER DATABASE [Recdit] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Recdit] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Recdit] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Recdit] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Recdit] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Recdit] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Recdit] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Recdit] SET  READ_WRITE 
GO


